### ISSUE TITLE
faucet idea

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-wallet#28]
## Description

faucet for a demo.

- Send ETH to a user visit at the first time.
- A user can get ETH anytime by clicking the button.

**Comment by shogochiai** [comment]
@syuhei176 
The source of fund is kinda Kovan faucet automation?

**Comment by syuhei176** [comment]
Yes!
this is too old issue ;) It's OK to close this issue if it doesn't required.
But It would be useful if it were.
